name: Auto Format with Prettier

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.{html,css,js}"
          commit_message: "chore: auto-format via Prettier"
