name: Prettier Format Check (No NPM)

on: [push, pull_request]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Prettier on HTML, CSS, and JS files
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check "**/*.{html,css,js}"
